@orbital_api_HostAddress = https://localhost:7024

### Diagnostic Requests
GET {{orbital_api_HostAddress}}/diag/cosmos-options
Accept: application/json
Content-Type: application/json

###

POST {{orbital_api_HostAddress}}/api/metadata/admin
Accept: application/json
Content-Type: application/json

{
    "type": "EventAttendanceModeEnumeration",
    "value": "Online",
    "displayName": "Online",
    "description": "Attendance Mode Online",
    "isActive": true,
    "sortOrder": 1
}


###
POST {{orbital_api_HostAddress}}/api/metadata/admin
Accept: application/json
Content-Type: application/json

{
    "Type": "EventStatusType",
    "Value": "Postponed",
    "DisplayName": "Postponed",
    "Description": "Event Status Postponed",
    "IsActive": true,
    "SortOrder": 1
}

###
GET {{orbital_api_HostAddress}}/api/metadata/eventStatus
Content-Type: application/json
Accept: application/json