@orbital_api_HostAddress = https://localhost:7024

POST {{orbital_api_HostAddress}}/api/metadata/admin
Accept: application/json
Content-Type: application/json

{
    "Type": "EventAttendanceModeEnumeration",
    "Value": "Online",
    "DisplayName": "Online",
    "Description": "Attendance Mode Online",
    "IsActive": true,
    "SortOrder": 1
}


###


GET {{orbital_api_HostAddress}}/api/metadata/eventStatus
Content-Type: application/json
Accept: application/json