@orbital_api_HostAddress = https://localhost:7024

POST {{orbital_api_HostAddress}}/api/metadata/admin
Accept: application/json
Content-Type: application/json

{
    "Type": "EventStatusType",
    "Value": "Scheduled",
    "DescriptionName": "Event Status Scheduled",
    "Description": "Evenet Status Scheduled Item",
    "IsActive": true,
    "SortOrder": 0
}


###


GET {{orbital_api_HostAddress}}/api/metadata/eventStatus
Content-Type: application/json
Accept: application/json